ryo-currency/ryo-currency

- src/crypto/random.c
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- rename `generate_keys` to `generate_legacy_keys`
- fix include dependancy
> fix windows compile

- src/blockchain_utilities/blockchain_blackball.cpp
- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/api/pending_transaction.cpp
- src/wallet/api/pending_transaction.h
- src/wallet/api/subaddress.cpp
- src/wallet/api/subaddress.h
- src/wallet/api/subaddress_account.cpp
- src/wallet/api/subaddress_account.h
- src/wallet/api/transaction_history.cpp
- src/wallet/api/transaction_history.h
- src/wallet/api/transaction_info.cpp
- src/wallet/api/transaction_info.h
- src/wallet/api/unsigned_transaction.cpp
- src/wallet/api/unsigned_transaction.h
- src/wallet/api/utils.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2.cpp
This PR fixes `make debug` compile issues.
- remove unused namespace creation `Bitmonero` in the global scope
- rename `Monero` namespace to `Ryo`
> fix wrong namespaces

- src/cryptonote_core/blockchain.cpp
If the network fork from difficulty algorithm v2 to v3 the timestamp array is smaller than required in the difficulty algorithm. This result in an illegal memmory access.
> fix illegal memory access

- src/cryptonote_basic/difficulty.cpp
The clamp values for the sum `L` are for one average time instead of `N`.
This results in an very heigh difficulty increase if `clamp_decrease` is limiting  `L`.
Multiplay the clamp values by `N` solves the issue.
> fix difficulty v3

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
Two conclusions from testing:
- Large check window is not an advantage.
- LOG_P can come up to -75.0
> make Poisson check stricter

- src/crypto/cn_slow_hash.hpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.h
It is currently not possible to compile ryo with clang.
All compiler issues withh be addressed with this PR.
- disable `#pragma GCC target("aes")` for clang (it is unknown)
- disable code not used variable
- fix initialize of an constexpr variable
> clang fixes

- src/CMakeLists.txt
- src/blockchain_utilities/CMakeLists.txt
- src/cryptonote_config.cpp
- src/daemon/CMakeLists.txt
- src/mnemonics/electrum-words.cpp
- src/simplewallet/CMakeLists.txt
- src/wallet/CMakeLists.txt
- tests/core_proxy/CMakeLists.txt
- tests/core_tests/CMakeLists.txt
- tests/unit_tests/CMakeLists.txt
- clang need the comparison operator defined as const if the object is const.
- fix
```
Undefined symbols for architecture x86_64:
"cryptonote::config<(cryptonote::network_type)0>::NETWORK_ID", referenced from:
nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> 
>::init(boost::program_options::variables_map const&) in librpc.a(instanciations.cpp.o)
```
> fix clang compile

- src/simplewallet/simplewallet.cpp
The address file is not created if the command line parameter `--create-address-file` is set.
Fix: - pass command line parameter into the wallet creation method
> fix address file is not created

- src/cryptonote_core/blockchain.cpp
Remove unused variables those was used in code which handles tx version one.
> remove left over code from monero

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
Implement stricter tx semantics rules:
- Only one pubkey per tx
- Only one extra pubkeys field per tx
- Extra pubkeys size must match outputs size
- Each input must have the same mixin size
- Activate sorted inputs check
> Implement stricter tx semantics

- src/wallet/wallet2.cpp
Thanks to @psychocrypt for finding it.
I left out `recover` flag. Unless it is triggered the wallet will optimise as if it was just created scanning only couple 1000 blocks, causing it to miss inputs.
> fix a bug in rescan_bc

- src/wallet/wallet2.cpp
- Change method back to sumokoin code, this function was accidental changed during the code base switch.
- Use latest fork v4 as base to approximate the blockchain height.
>  fix `get_approximate_blockchain_height`

- src/wallet/wallet2.cpp
- ignore the field `refresh_height` stored together the key
- add new field `refresh_height2`
If `refresh_height2` is not available e.g. in old wallet files than the value will
be set to zero.
> new field `refresh_height2` in *.keys

- src/simplewallet/simplewallet.cpp
If the wallet detects the refresh bug where the balance is not shown correctly due to
a wrong internal variable the wallet will throw an message for the user and recommend to
restore the wallet from the seed.
> simplewallet: warning if bug is detected

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
Add an optional argument to `rescan_bc` to specialize the height to start the rescan.
The default if no argument is equal to the behavior before and start syncing from an optimized height.
- fix documentation of `refresh`
- extend `rescan_bc` with optional argument
- if a start height is given for: `rescan_bc` and `refresh` a non optimized refresh without skipping blocks before the wallet creation is performed
- wallet2: `m_explicit_refresh_from_block_height` was never used in the code before.
- `m_explicit_refresh_from_block_height`
- enabling that transactions in `process_new_blockchain_entry` are ignored if they are older than the wallet.
- enabling that `m_refresh_from_block_height` is used to optimize the start height
> simplewallet: `rescan_bc` add optional argument

- Dockerfile
The cmake find script for readline depends on ncurses.
This is not documented and the result is that RYO build always without readline support.
source: https://github.com/bro/cmake/blob/9a9bbd29413ed6eba645e09628ba8eed8232603f/FindReadline.cmake#L34
readline is to support e.g. the arrow usage in the cli wallet and the daemon.
- add build recipe for ncureses to the docker container
> fix readline support for docker

- tests/unit_tests/base58.cpp
- fix test for `get_account_address_from_str()`
- add test for sumo coin address
- add test for ryo long address
- add test for ryo kurz address
> fix unittest base58

- src/cryptonote_config.h
- tests/unit_tests/block_reward.cpp
- fix block reward tests
- remove `FINAL_SUBSIDY_PER_MINUTE` (left over from monero and itherefore not used)
- extent macro `TEST_ALREADY_GENERATED_COINS` with the block-height for testing
> fix tests for block reward

- src/common/CMakeLists.txt
- src/common/boost_locale.cpp
- src/mnemonics/CMakeLists.txt
- src/mnemonics/electrum-words.cpp
- src/simplewallet/CMakeLists.txt
- src/wallet/CMakeLists.txt
Since #82 the windows compile is broken. There are many linker issue.
- separate `boost_local.hpp` into `hpp` and `cpp` to avoid that the library common is moving the boost locale dependency into all targets
- link icu mnemonics library
- remove boost locale library from all targets those have no dependency to this library
> fix compile with boost local

- src/wallet/wallet2.cpp
During the URI parsing an index outside of the string is used if the URI is shorter than `7` characters.
This will trigger an exeption.
- remove the hard coded position of `:`
- improve the error message
> fix URI parsing

- src/cryptonote_basic/hardfork.cpp
- src/cryptonote_basic/hardfork.h
- src/cryptonote_core/blockchain.h
- src/wallet/node_rpc_proxy.cpp
- src/wallet/wallet2.cpp
Somebody had a stunning idea of combining two states ( `earliest_height` and `enabled` ) into a single value and caching them together. The problem is while `earliest_height` doesn't change on the fork, `enabled` does. So if we make the call when `enabled` = `false` (aka before the fork), we will never apply the rules for that fork until the wallet is restarted and the cache clears.
> Monero caching bug

- src/blockchain_utilities/blockchain_blackball.cpp
- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/blockchain_usage.cpp
- src/debug_utilities/cn_deserialize.cpp
- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_args.cpp
- src/wallet/wallet_args.h
- src/wallet/wallet_rpc_server.cpp
If the user ask the app to show the help the most binaries currently returning the exit code `1`.
Asking for a the help message and get them showed without errors must be return the exit code zero because the user requested action is fulfilled.
- return exit code zero user request `-h/--help`
- return exit code zero if `--version` is requested and a valid cli option
> fix wrong exit code for `--help`

- src/crypto/crypto.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Three fixes rolled into one:
- Uninitialised access to `m_wallet` causing a crash
- Extra security for `hash_secret` to prevent padding from screwing up key generation (default, 4, is ok)
- Prompt user for the missing metadata if 12-word seed was used.
> Wallet fixes

- .travis.yml
- tests/gtest/CMakeLists.txt
Since #89 the travis tests are broken. The selected compiler is not used because the wrong environment variables names are used to select the compiler.
> fix broken travis tests

- src/crypto/random.cpp
Simple omission of `!` (return value is BOOL)
> fix CryptGenRandom return val

- .travis.yml
- src/cryptonote_basic/account.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server_commands_defs.h
fix error like `src/cryptonote_basic/account.cpp:185:31: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘using secret_key = struct tools::scrubbed<crypto::ec_scalar>’ {aka ‘struct tools::scrubbed<crypto::ec_scalar>’}; use assignment or value-initialization instead [-Werror=class-memaccess]`
- remove usage of `memset` to reset complex types like `std::vector`
- add `clear()` method to `txpool_stats`
- travis CI add gcc 8 toolchain
>  fix gcc8 compile under linux

- src/cryptonote_core/tx_pool.cpp
`tx_pool` is going into an endless loop if there is no meta record for a tx hash available.
x-ref: https://github.com/monero-project/monero/pull/4276
> fix possible infinite loop in `tx_pool`

- src/simplewallet/simplewallet.cpp
Given indicies will not be parsed due to a logic mistake.
fix imported from monero: https://github.com/monero-project/monero/commit/3a4c3ac89104323cb72df4e2102c4563c92be2df
> simplewallet: fix unspend output

- src/wallet/wallet2.cpp
- avoid division by zero if daemon provided block size limit is lesser than two.
import of monero pull request: https://github.com/monero-project/monero/pull/4202
> Wallet: fix division by zero

- src/wallet/CMakeLists.txt
- src/wallet/wallet_args.cpp
Applies the same fix from simplewallet (https://github.com/ryo-currency/ryo-currency/blob/master/src/simplewallet/simplewallet.cpp#L7659) to the RPC. 
Fixes opening of wallet files with international characters in the filename.
> Windows Internationalization Fixes

- src/address_validator/address_validator.cpp
- src/blockchain_utilities/blockchain_blackball.cpp
- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/blockchain_usage.cpp
- src/common/command_line.cpp
- src/common/command_line.h
- src/daemon/main.cpp
- src/daemonizer/daemonizer.h
- src/daemonizer/posix_daemonizer.inl
- src/daemonizer/windows_daemonizer.inl
- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_args.cpp
- src/wallet/wallet_rpc_server.cpp
Background (or let's go back to 1993):
Windows internally uses USC2 encoding. This is a grandfather of UTF-16, back from the days where 16 bits was enough for everyone.
Every single windows API function has two variants. W and A - the latter calling the W function and **converting the result to local codepage**. This is important as this isn't a lossless conversion. If the USC2 glyphs are not in user's codepage, they cannot be recreated (as Monero guys attempted to do here https://github.com/ryo-currency/ryo-currency/pull/102/commits/5762596a4876e23a4e09d218b509692346d976ed#diff-cb82e0aa6db499004305bf35f0eaafbcL161)
So the key to unicode support on Windows is to make sure either we or the underlying library calls the W variant function and then converts to UTF8. Since Windows is best at …
> Implement Windows Unicode APIs

- src/wallet/wallet_rpc_server.cpp
Open the wallet on restore in line with the behaviour on create.
Also fix some wonky indenting.
> Open wallet on restore

- src/address_validator/address_validator.cpp
- src/blockchain_utilities/blockchain_blackball.cpp
- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/blockchain_usage.cpp
- src/common/command_line.cpp
- src/common/command_line.h
- src/daemon/main.cpp
- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_rpc_server.cpp
Using `std::string` in this context produced a bug where small string optimisations kicked in. Since this is C-style API, I opted for C-style method of a single combined-string buffer instead.
The buffer is not deleted at all. The only safe place where we can do it is just before the program close. And once my professor compared that kind of thing to cleaning up your bedroom just before a wrecking ball drives through your house.
> fix windows cmd line

- src/wallet/wallet2.cpp
During the scan of key images for sweeped transfers memory outside of the range of requested key images is accessed.
https://github.com/ryo-currency/ryo-currency/blob/59a7b4ce2c1d1f02567fbcd009e337d19a87d345/src/wallet/wallet2.cpp#L8634
This fix also avoid that transfers without a key image will be scanned during the import of keys.
- change the loop to scan only as much transaction as we have signed key images
import of monero pull request: https://github.com/monero-project/monero/pull/4041
> fix invalid memory access

- src/wallet/wallet_rpc_server.cpp
This should be left at default value
> Fix lookahead setting on restored wallets

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
This is a much more comprehensive fix than what you spotted @psychocrypt 
- typeless C-style NULL macro has been exorcised
- backend start / stop is now state-safe
- wallet metadata is saved on_close
- if for whatever reason the exe is normally terminated without saving the state it will attempt to do so
> Fix wallet start / stop

- src/wallet/wallet2.cpp
Fix for a duplicate outpk exploit. https://github.com/monero-project/monero/pull/3995
As usual our friends forgot to inform everyone else about a security problem
> fix outpk dup bug

- src/cryptonote_core/cryptonote_core.cpp
fix #121
Fix value underflow in the case where the first block with the premine is not included
within the scaned blocks.
> fix `get_coinbase_tx_sum()`

- src/wallet/wallet2.cpp
- fix usage of wrong vector
import of Monero PR: https://github.com/monero-project/monero/pull/4347
Co-authored-by: psychocrypt <psychocryptHPC@gmail.com>
> wallet2: fix secondary partially signed multisig txes

- src/wallet/wallet2.cpp
In a case where the refresh fails, throw an error.
Import of the Monero PR: https://github.com/monero-project/monero/pull/4360
> wallet2: throw exception on refresh error

- src/common/dns_utils.cpp
import Monero PR: https://github.com/monero-project/monero/pull/4463
> dns_utils: refresh list of usable DNSSEC servers

- src/common/dns_utils.cpp
DNS anchors is updated on 11th of october 2018.
https://www.icann.org/resources/pages/ksk-rollover
import of Monero pr: https://github.com/monero-project/monero/pull/4309
> dns_util: add new DNSSEC trust anchor for rollover

- contrib/epee/include/net/local_ip.h
Apparently this was written by someone who did not understand how netmasks work. 
In particular it was failing `172.16.0.0` test case. Scrapped the whole code and rewrote.
> Fix local ip check

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/cryptonote_core/blockchain.cpp
This fixes the issue where the wallet complains that the transaction has vouts but no indices by feeding a dummy index. This will technically create a problem for the wallet owning the vout public key - but I have the only mainnet wallet where that applies.
> Enable blockchain to check for bad vouts

- src/crypto/CMakeLists.txt
Missed that one when downgrading the code to SSE2
> Change clang settings to SSE2

- src/cryptonote_basic/difficulty.cpp
Timestamp limits can invalidate the `highest timestamp must higher than the lowest` condition. It needs to be checked last since it takes precedence.
> Fix diff interpolation

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- Remove OptimizeCoinbase wallet refresh mode. It is not relevant for us.
- Remove the tx pub key scanning silliness, it looks like it was written by a first grader and only led to security problems in the past.
> Remove OptimizeCoinbase refresh

- external/unbound/configure_checks.cmake
fix #150 
- port of https://github.com/monero-project/unbound/pull/11
> libunbound: fix MinGW compile

- src/crypto/pow_hash/cn_slow_hash.hpp
fix #190
AVX2 can be disabled by the OS. This can be detected by checking the
osxsave bit.
> fix avx2 detection

- contrib/epee/src/CMakeLists.txt
This fixes a condition where improperly detected libreadline will result in linking `readline_buffer.cpp` without `HAVE_READLINE` 
-(possibly) Detect readline properly on msys2
> libreadline fix on msys2

- contrib/epee/demo/iface/transport_defs.h
- contrib/epee/include/net/jsonrpc_structs.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/include/serialization/keyvalue_serialization.h
- contrib/epee/tests/src/storages/portable_storages_test.h
- src/checkpoints/checkpoints.cpp
- src/cryptonote_basic/account.cpp
- src/cryptonote_basic/account.h
- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_stat_info.h
- src/cryptonote_basic/miner.h
- src/cryptonote_basic/subaddress_index.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/daemon/rpc_command_executor.cpp
- src/device/device_default.cpp
- src/p2p/net_node.h
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/net_load_tests/net_load_tests.h
Not initialized memory can be send out over the rpc server.
This can be used to readout parts of the main memory.
- default initialize response data
Co-authored-by: fireice-uk <fireice-uk@users.noreply.github.com>
> fix mem leakage

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/common/bloom_filter.hpp
- src/common/gulps.hpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/CMakeLists.txt
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_tx_scan.cpp
- tests/unit_tests/hardfork.cpp
Upgrade multithreading in the wallet to something that has actually a fighting chance of maxing out the CPU.
- Use of 64 bit lib is conservative, there is no way to produce anything but false negatives if there is an exploitable problem there.
- We strip away the abstraction layers in 64 bit code (mostly to avoid giving a blueprint for a parallel hw wallet implementation to guys that should really have been able to figure it out on their own)
- Bottleneck now is the block feed speed
- Time improvement will vary depending on the point above. HDDs won't see a lot. High IOPS NVMe SSDs will improve most. Overall 2 to 5x is a good ballpark figure so far.
> Multi-threaded wallet scan

- CMakeLists.txt
The old version number was wrong and in the wrong format
> fix boost version check in CMake

- CMakeLists.txt
Fix usage of wrong syntax within an if condition to compare a string
with a cmake variable.
> fix cmake (broken windows compile)

- contrib/epee/include/net/abstract_tcp_server2.inl
Native handle is a struct on macos - unlike integer type on Linux and Windows. Printing it as as a value is pretty pointless, we can get different values for the same thread. Use thread_id instead.
> Fix build for maos

- src/wallet/wallet2_tx_scan.cpp
If a tx is sended and in the last block the spent and received amount
will be shown with each background refresh.
> fix block scan

- src/simplewallet/simplewallet.cpp
Output messages was written after the promt. This results in messages
without color (even error), unreadable and not copyable output.
- disable promt for all output
BUG was introduced with GULPS
> simplewallet: fix output

- src/daemon/command_line_args.h
- src/daemon/main.cpp
- src/wallet/wallet_args.cpp
If log-file is set, log-file-level will have a reasonable default now, instead of being empty (i.e no logging)
> Fix disparities and edge cases in log-file-level

- src/simplewallet/simplewallet.cpp
Hey,
Locked blocks transfer for 1000000 blocks is approximate 8 years (~8 yrs). So `if (locked_transfer > 1000000)` the `GULPS_PRINT_FAIL` message should be `"Locked blocks too high, max 1000000 (˜8 yrs)"`.
If this is okay let me know, I can also change the number in the other files. If the 4 years is meant to stay and not change, then the if statement should change to:
```
if(locked_blocks > 500000)
{
GULPS_PRINT_FAIL(tr("Locked blocks too high, max 500000 (˜4 yrs)"));
return true;
}
```
P.S. I'm not sure if this is the way of submitting a PR to Ryo's codebase. Created a brand new branch with the specific name to what is being suggested. If something needs to be changed let me know. 
Thank you
:)
> Changed approximate time for locked_transfer command
