ryo-currency/ryo-currency

- Dockerfile
set blockchain data folder to /root/.ryo
> fix Docker image

- tests/core_tests/block_validation.cpp
Variable `DIFFICULTY_WINDOW` is unknown.
Rename `DIFFICULTY_WINDOW` to `common_config::DIFFICULTY_WINDOW_V1`
> fix test compiling

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
Squash the bug that did this to our pool:
It will make 3 block rewards that we mined there permanently unspendable.
> fix for db bug

- src/cryptonote_core/blockchain.cpp
This sets the fork date to 7th of July.
> Push back fork date

- src/crypto/cn_slow_hash.hpp
cherry-pick https://github.com/sumoprojects/sumokoin/pull/107
> Use boost for aligned alloc

- src/cryptonote_core/blockchain.cpp
import of the Monero PR: https://github.com/monero-project/monero/pull/3919
> take care that blockchain is not read only available

- src/rpc/core_rpc_server.cpp
> is_ready fix

- src/wallet/wallet2.cpp
xref https://github.com/monero-project/monero/pull/3985
> fix tx double scan

- src/version.cpp.in
increase version for the second bug-fix release
> increase version to 0.2.0.2

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Tested and ready to merge.
Monero x-ref https://github.com/monero-project/monero/pull/4117
> Monero fix #2

- src/checkpoints/checkpoints.cpp
add block 150000 (v4 fork) height to the checkpoints
> update checkpoints with v4 block

- contrib/epee/include/net/http_client.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
Make simplewallet properly handle exceptions thrown in make_basic, as well as adding a new one
> Prompt if daemon-address is incomplete

- src/common/download.cpp
- src/simplewallet/simplewallet.cpp
Fix a few warnings about maybe uninitilized values.
> fix warnings

- src/cryptonote_core/blockchain.cpp
Avoid that searching for the commulative difficulty after an invalid request.
This commit is imported from Monero: https://github.com/monero-project/monero/commit/d95bc44c6ba2a1096ca95d1565851e5827f48e4f
> fix invalid block data usage

- src/cryptonote_core/blockchain.cpp
Diff is slightly screwed since I moved a section. This pr simply moves everything into a single if and adds a no pub key error.
> Clean up and add a no pub key check

- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_basic/miner.cpp
- src/cryptonote_config.cpp
- src/cryptonote_config.h
- src/daemon/command_parser_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- tests/unit_tests/address_from_url.cpp
Ready to merge (please run a simple test)
> Stop people from mining to dev fund

- src/version.cpp.in
bump version for the next release
> version increase to 0.3.0.0

- src/CMakeLists.txt
- src/blockchain_db/CMakeLists.txt
- src/checkpoints/CMakeLists.txt
- src/common/CMakeLists.txt
- src/crypto/CMakeLists.txt
- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_core/CMakeLists.txt
- src/cryptonote_protocol/CMakeLists.txt
- src/daemonizer/CMakeLists.txt
- src/device/CMakeLists.txt
- src/mnemonics/CMakeLists.txt
- src/multisig/CMakeLists.txt
- src/p2p/CMakeLists.txt
- src/ringct/CMakeLists.txt
- src/rpc/CMakeLists.txt
- src/serialization/CMakeLists.txt
- src/wallet/CMakeLists.txt
- src/wallet/api/CMakeLists.txt
rename `monero_add_library` to `ryo_add_library`
> CMake rename `monero_add_library`

- src/blockchain_utilities/CMakeLists.txt
- src/common/boost_locale.hpp
- src/gen_multisig/CMakeLists.txt
- src/mnemonics/electrum-words.cpp
- src/mnemonics/electrum-words.h
- src/mnemonics/russian.h
- src/simplewallet/CMakeLists.txt
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/CMakeLists.txt
- src/wallet/wallet_rpc_server.cpp
Replaced current confused mess with a cleaner system where mnemonic language is only requested when needed, and that request can be filled from user input or cmd line.
> Mnemomnic language cleanup

- .travis.yml
- tests/core_tests/CMakeLists.txt
- tests/difficulty/CMakeLists.txt
- compile test cases and run unit_tests
- disable runtime tests `core_tests` and `difficulty` (must be fixed in a separate PR)
- refactor travis
> extent travis CI tests

- src/version.cpp.in
version increase for the next release
> update version to 0.3.1.0

- src/wallet/wallet2.cpp
fix bug: https://getmonero.org/2018/09/25/a-post-mortum-of-the-burning-bug.html
- import fix from Monero https://github.com/monero-project/monero/pull/4438/commits/e350cc5ad557eba67790551f96bbbcfc97173480
- rename variable to avoid `var_1`, `var_2` without any meaning
Co-authored-by: moneromooo-monero <moneromooo-monero@users.noreply.github.com>
> fix burning bug

- src/wallet/wallet2.cpp
transfers between subaddresses hitting the sanity check
import of monero pull request: https://github.com/monero-project/monero/pull/4461
> fix faild subaddress sanity check

- src/common/dns_utils.cpp
- src/version.cpp.in
- src/wallet/wallet2.cpp
- dns_utils: refresh list of usable DNSSEC servers #132
- dns_util: add new DNSSEC trust anchor for rollover #131 
- fix faild subaddress sanity check #129
> Point Release v0.3.1.2

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- Also changed filename security slightly
> wallet_rpc: keyimg is now binary

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
Import of monero-project/monero#4269
Authored by: anonimal <anonimal@getmonero.org>
> Added change_wallet_password RPC call (port from monero codebase)

- src/wallet/wallet2.cpp
> Fix swept_outputs issues

- src/version.cpp.in
> increase version to 0.3.2.0

- CMakeLists.txt
Minor change enabling proper debug testing.
> Set NDEBUG only on release

- .gitignore
- utils/symlink-wallets.sh
Simple script for easy preservation of wallets through `make clean`
> utils script to symlink testnet wallets

- src/cryptonote_basic/difficulty.cpp
- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/ts_interpolation.cpp
- Cleaned up confusion regarding `DIFFICULTY_WINDOW_V3` vs `DIFFICULTY_BLOCKS_COUNT_V3` in the current algo.
- Added a new quadratic algo that tends to favour newer results.
> QWMA diff algo

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- Optimise `pick_preferred_rct_inputs`
- Fix #145 
- Implement seamless max out handling
> Various wallet issues

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemonizer/windows_service.cpp
- src/ringct/rctSigs.cpp
- src/simplewallet/simplewallet.cpp
- Few ports from Monero
- Canonical check (different place from Monero)
- Uniform payment ID notification
> Minor fixes

- src/crypto/CMakeLists.txt
- src/crypto/pow_hash/cn_slow_hash.hpp
- src/crypto/pow_hash/cn_slow_hash_hard_intel.cpp
- src/crypto/pow_hash/cn_slow_hash_intel_avx2.cpp
- src/crypto/pow_hash/hw_detect.hpp
- Windows build fix
- Windows crash fix
- ARM fixes
- Clang build fix
> PoW build fixes

- src/cryptonote_basic/miner.cpp
Fix taken from https://github.com/masari-project/masari/pull/163
> Fix Boost 1.69

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- Approx 14th of Feb at 12.00 then 20.00 UTC
> Set mainnet forking schedule

- contrib/epee/include/net/levin_client_async.h
- contrib/epee/include/net/levin_protocol_handler_async.h
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/common/password.cpp
- src/cryptonote_core/blockchain.cpp
- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_args.cpp
- src/simplewallet/simplewallet.cpp
- translations/ryo.ts
- translations/ryo_fr.ts
- translations/ryo_it.ts
- translations/ryo_sv.ts
X-ref list:
https://github.com/monero-project/monero/pull/3414
https://github.com/monero-project/monero/pull/3583
https://github.com/monero-project/monero/pull/3798
https://github.com/monero-project/monero/pull/3677
https://github.com/monero-project/monero/pull/3957
https://github.com/monero-project/monero/pull/4173
https://github.com/monero-project/monero/pull/4742
https://github.com/monero-project/monero/pull/4933
https://github.com/monero-project/monero/pull/4502
Authors are numerous.
> Backport typos from Monero

- README.md
This PR is a WIP as I would like to add verbage for exporting the blockchain to a file as well. I was wanting to get some feedback early on my wording and any suggestions for improving before completing this feature / PR. 
I am not sure how to link to issues on github but the issue I am trying to resolve is #178.
Thanks,
-KM
> Add verbage to the readme to outline the process for importing blockchain data from a file

- src/common/gulps.hpp
- src/daemon/main.cpp
- src/rpc/core_rpc_server.cpp
- src/simplewallet/simplewallet.cpp
- tests/unit_tests/main.cpp
- activate `set_log` for `ryod` and `simplewallet`
> re-add `set_log` command

- src/rpc/core_rpc_server.cpp
> fix log message

- README.md
> syntax fix in docs.

- src/gen_multisig/gen_multisig.cpp
Improper output config caused no display.
> Fix for gen-multisig display

- src/crypto/pow_hash/cn_slow_hash_soft.cpp
As discussed in the group chat, issue #212 is fixed. Ignore PR #213 as it was edited on the wrong branch
> Fixed issue #212

- src/common/gulps.hpp
- src/common/thdq.hpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2_tx_scan.cpp
> optimze queue lock handling

- src/cryptonote_core/blockchain.cpp
Avoid that `already_generated_coins` can be larger than the allowed
`MONEY_SUPPLY`
PR imported from monero: https://github.com/monero-project/monero/pull/5819
> fix alt chain coin overflow

- src/cryptonote_core/cryptonote_core.cpp
In theory someone can just spam bad txes to flood the screen
> Topic silence tx error

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2_tx_scan.cpp
- Subaddress funds were not detected properly
- Blockchain detachment lost some blocks on reorgs, leading to wallet exceptions
- Received funds were printed white and not magenta with readline
> Fix scanning issues

- src/device/device_ledger.cpp
- src/wallet/wallet2.cpp
clarify account no unlocked balance error message
[Reference PR](https://github.com/monero-project/monero/pull/6793)
> language cleanup and fix some typos

- contrib/epee/include/net/network_throttle-detail.hpp
- contrib/epee/include/net/network_throttle.hpp
- contrib/epee/src/network_throttle-detail.cpp
- src/common/util.cpp
- src/common/util.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Squashed the commits and making a new PR to keep master branch git history clean.  Still has the issue of printing the lines twice though.  Will close my earlier PR.
> Add print_net_stats

- src/crypto/crypto.h
- src/crypto/hash.h
> add extra types to fmt
